version: "3.7"
services:
  npm:
    container_name: "kuromoji-npm"
    build:
      context: docker/kuromoji
      dockerfile: Dockerfile
    volumes:
      - "./kuromoji:/kuromoji:delegated"
    working_dir: /kuromoji
    entrypoint: ["npm"]

  build-dict:
    container_name: "kuromoji-build-dict"
    build:
      context: docker/kuromoji
      dockerfile: Dockerfile
    volumes:
      - "./kuromoji:/kuromoji:delegated"
      - "./project:/project:delegated"
      - "./docker/kuromoji/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:cached"
    working_dir: /kuromoji
    environment:
      - DICT_SRC=/project/config/kuromoji/user-dic.csv
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
